require:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-sequel

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'Gemfile'
    - 'vendor/**/*'
    - 'lib/inferno/db/schema.rb'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'dev_suites/ui_onc_program/**/*'
    - 'dev_suites/ui_smart_scheduling_links/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: 'indented'

Lint/EmptyBlock:
  Exclude:
    - 'dev_suites/ui_onc_program/**/*'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false
    
Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/OpenStructUse:
  Exclude:
    - 'spec/**/*'

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

# Use code climate's metrics measurement rather than rubocop's
Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/requests/**/*'

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  CustomTransform:
    OAuthCredentials: oauth_credentials

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NotToNot:
  EnforcedStyle: to_not

# Following this rule's suggestions breaks postgres support
Sequel/ConcurrentIndex:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false
