services:
  nginx:
    image: nginx
    volumes:
      - ./config/nginx.background.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    command: [nginx, '-g', 'daemon off;']
    depends_on:
      - hl7_validator_service
      - fhirpath
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
  hl7_validator_service:
    image: infernocommunity/inferno-resource-validator
    # Update this path to match your directory structure
    volumes:
      - ./data/igs:/app/igs
      # To let the service share your local FHIR package cache,
      # uncomment the below line
      # - ~/.fhir:/home/ktor/.fhir
  fhirpath:
    image: infernocommunity/fhirpath-service
    ports:
      - "6789:6789"
