FROM markiantorno/validator-wrapper

USER root
# Java certs need to be installed as root, so switch to that user for this step only
# (the image does not contain 'sudo')
RUN wget https://gitlab.mitre.org/mitre-scripts/mitre-pki/-/raw/master/tool_scripts/install_certs.sh -O - | MODE=java sh

USER $APPLICATION_USER

# CMD is inherited from parent image as long as we don't override it or ENTRYPOINT
