version: '3'
services:
  validator_service:
    extends:
      file: ./lib/inferno/apps/cli/services/docker-compose.global.yml
      service: validator_service
    volumes:
      - ./data/igs:/home/igs
  fhir_validator_app:
    extends:
      file: ./lib/inferno/apps/cli/services/docker-compose.global.yml
      service: fhir_validator_app
  nginx:
    extends:
      file: ./lib/inferno/apps/cli/services/docker-compose.global.yml
      service: nginx
    volumes:
      - ./config/nginx.background.conf:/etc/nginx/nginx.conf
  redis:
    extends:
      file: ./lib/inferno/apps/cli/services/docker-compose.global.yml
      service: nginx
    volumes:
      - ./data/redis:/data
  hl7_validator_service:
    extends:
      file: ./lib/inferno/apps/cli/services/docker-compose.global.yml
      service: hl7_validator_service
    # Update this path to match your directory structure
    volumes:
      - ./data/igs:/app/igs
      # To let the service share your local FHIR package cache,
      # uncomment the below line
      # - ~/.fhir:/home/ktor/.fhir
  fhirpath:
    extends:
      file: ./lib/inferno/apps/cli/services/docker-compose.global.yml
      service: fhirpath
