source 'https://rubygems.org'

gem 'jekyll', '~> 4.3'
gem 'kramdown-parser-gfm', '~> 1.1'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:windows, :jruby]

gem 'webrick', '~> 1.9'
